---
# Copyright (c) 2020 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Ask user if /etc/apt/sources.list should really be removed
  when: not force_apt_sources_list_removal
  pause:
    echo: yes
    prompt: "Do you really want to remove /etc/apt/sources.list? (yes/no)"
    register: removal_question

- name: Remove /etc/apt/sources.list if user approved removal
  when: force_apt_sources_list_removal or removal_question.user_input == 'yes'
  file:
    path: /etc/apt/sources.list
    state: absent
